version: "3"
services:
  capture:
    image: registry.cn-qingdao.aliyuncs.com/wod/movie_data_capture:v6.7.2
    restart: "no"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /volume1/capture/config:/config
      - /volume1/capture/data:/data
